# SPDX-FileCopyrightText: 2025 Christian Rath-Ulrich
#
# SPDX-License-Identifier: GPL-3.0-or-later

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Cru\Psr14EventList\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  Cru\Psr14EventList\Command\EventListCommand:
    tags:
      - name: console.command
        command: 'cru:list-psr14-events'
        description: 'Shows available PSR-14 Events'